### PR TITLE
Load of DefaultDB in Guice + depedendcies updates

### PR DESCRIPTION
**Pull request by renatocaval**
- fixes loading of DefaultDB in Guice 
- dependencies updates
- use Slick profiles instead of drivers

### CODE REVIEW

**Comment by TimMoore** [comment]
I'm getting a compile error on `cors-scala`:

```
[error] /Users/tmoore/Projects/lagom/lagom-recipes/cors/cors-scala/cors-scala-impl/src/main/scala/com/lightbend/lagom/recipes/corsscala/impl/CorsscalaLoader.scala:35:21: overriding value httpFilters in class LagomApplication of type Seq[play.api.mvc.EssentialFilter];
[error]  lazy value httpFilters cannot override a concrete non-lazy value
[error]   override lazy val httpFilters: Seq[EssentialFilter] = Seq(corsFilter)
[error]                     ^
[error] one error found
[error] (cors-scala-impl / Compile / compileIncremental) Compilation failed
[error] Total time: 17 s, completed 29/01/2018 4:15:06 PM
```

**Comment by TimMoore** [comment]
The i18n recipe was not updated.

**Comment by TimMoore** [comment]
I ran through each project and found a few deprecation warnings that we should fix up (either here or in a separate PR):

The first category is references to `akka.testkit.JavaTestKit`:

```
[warn] /Users/tmoore/Projects/lagom/lagom-recipes/consumer-service/consumer-service-java-sbt/hello-impl/src/test/java/com/lightbend/lagom/recipes/consumer/hello/impl/HelloEntityTest.java:5:1: akka.testkit.JavaTestKit in akka.testkit has been deprecated
[warn] import akka.testkit.JavaTestKit;
[warn] /Users/tmoore/Projects/lagom/lagom-recipes/consumer-service/consumer-service-java-sbt/hello-impl/src/test/java/com/lightbend/lagom/recipes/consumer/hello/impl/HelloEntityTest.java:28:1: akka.testkit.JavaTestKit in akka.testkit has been deprecated
[warn]         JavaTestKit.shutdownActorSystem(system);
```

```
[warn] /Users/tmoore/Projects/lagom/lagom-recipes/mixed-persistence/mixed-persistence-java-sbt/hello-impl/src/test/java/com/lightbend/lagom/recipes/mixedpersistence/hello/impl/HelloEntityTest.java:5:1: akka.testkit.JavaTestKit in akka.testkit has been deprecated
[warn] import akka.testkit.JavaTestKit;
[warn] /Users/tmoore/Projects/lagom/lagom-recipes/mixed-persistence/mixed-persistence-java-sbt/hello-impl/src/test/java/com/lightbend/lagom/recipes/mixedpersistence/hello/impl/HelloEntityTest.java:34:1: akka.testkit.JavaTestKit in akka.testkit has been deprecated
[warn]         JavaTestKit.shutdownActorSystem(system);
```
(Looks like we're still using it [in the template](https://github.com/lagom/lagom-java.g8/blob/33f9862fb09936986b089bacb646cee4385c8c68/src/main/g8/%24name__norm%24-impl/src/test/java/%24package%24/impl/%24name__Camel%24EntityTest.java), too.)

The second category is references to `play.crypto.secret`:

```
12:44:49.460 [warn] application [] - application.conf @ file:/Users/tmoore/Projects/lagom/lagom-recipes/consumer-service/consumer-service-java-sbt/hello-impl/target/scala-2.12/classes/application.conf: 4: play.crypto.secret is deprecated, use play.http.secret.key instead
```

```
16:11:20.390 [warn] application [] - application.conf @ file:/Users/tmoore/Projects/lagom/lagom-recipes/cors/cors-java/cors-java-impl/target/scala-2.12/classes/application.conf: 4: play.crypto.secret is deprecated, use play.http.secret.key instead
```

```
16:20:10.943 [warn] application [] - application.conf @ file:/Users/tmoore/Projects/lagom/lagom-recipes/http-header-handling/http-header-handling-java-sbt/hello-impl/target/scala-2.12/classes/application.conf: 1: play.crypto.secret is deprecated, use play.http.secret.key instead
```

```
16:44:10.511 [warn] application [] - application.conf @ file:/Users/tmoore/Projects/lagom/lagom-recipes/mixed-persistence/mixed-persistence-scala-sbt/hello-impl/target/scala-2.12/classes/application.conf: 3: play.crypto.secret is deprecated, use play.http.secret.key instead
```

I think we can just remove these (we already removed them from the templates). It needs to be specified to run in production, but these recipes aren't really meant to run in production and we shouldn't encourage people to put the secret into an `application.conf` in git.

This one required enabling `-deprecation` to see the full warning:

```
[warn] /Users/tmoore/Projects/lagom/lagom-recipes/mixed-persistence/mixed-persistence-scala-sbt/hello-api/src/main/scala/com/lightbend/lagom/recipes/hello/api/HelloService.scala:21:36: Eta-expansion of zero-argument method values is deprecated. Did you intend to write HelloService.this.allGreetings()?
[warn]         pathCall("/api/greetings", allGreetings _)
[warn]                                    ^
[warn] one warning found
```

(Maybe there's a standard set of `scalac` flags we should enable by default in the giter8 template?)

**Comment by renatocaval** [comment]
@TimMoore I fixed all the issues you mentioned. Ready for a second review round.

**Comment by TimMoore** [comment]
I noticed a few other errors (I think these were there last time, too but I didn't notice).

```
2018-01-30T06:00:04.055Z [warn] akka.actor.ActorSystemImpl [sourceThread=application-akka.actor.default-dispatcher-4, akkaSource=akka.actor.ActorSystemImpl(application), sourceActorSystem=application, akkaTimestamp=06:00:04.054UTC] - Illegal header: Illegal 'etag' header: Invalid input 's', expected 'W' or opaque-tag (line 1, column 1): some-value-stored-in-db-or-persistent-entity
^
2018-01-30T06:00:43.931Z [warn] akka.actor.ActorSystemImpl [sourceThread=application-akka.actor.default-dispatcher-2, akkaSource=akka.actor.ActorSystemImpl(application), sourceActorSystem=application, akkaTimestamp=06:00:43.931UTC] - Illegal header: Illegal 'if-none-match' header: Invalid input 's', expected ws or entity-tag (line 1, column 1): some-value-stored-in-db-or-persistent-entity
^
[WARN] [01/30/2018 16:30:43.941] [hello-impl-internal-dev-mode-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(hello-impl-internal-dev-mode)] Illegal header: Illegal 'if-none-match' header: Invalid input 's', expected ws or entity-tag (line 1, column 1): some-value-stored-in-db-or-persistent-entity
^
2018-01-30T06:00:49.980Z [warn] akka.actor.ActorSystemImpl [sourceThread=application-akka.actor.default-dispatcher-11, akkaSource=akka.actor.ActorSystemImpl(application), sourceActorSystem=application, akkaTimestamp=06:00:49.980UTC] - Illegal header: Illegal 'if-none-match' header: Invalid input 'i', expected ws or entity-tag (line 1, column 1): invalid-etag
^
[WARN] [01/30/2018 16:30:49.983] [hello-impl-internal-dev-mode-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(hello-impl-internal-dev-mode)] Illegal header: Illegal 'if-none-match' header: Invalid input 'i', expected ws or entity-tag (line 1, column 1): invalid-etag
^

```

This is when testing the `http-header-handling-java-sbt` project. Akka HTTP is more strict about HTTP header format than Netty, and I think this is an error in the test.

**Comment by TimMoore** [comment]
The deprecated `JavaTestKit` use is still in `consumer-service-java-sbt`.

**Comment by TimMoore** [comment]
Pushed fixes for the two remaining issues I found. I think this is ready to merge if you're happy.

**Pull request merged**
